### ISSUE TITLE
Deploy to Heroku

### ISSUE THREAD

**Issue by karpinovsky** [karpinovsky/kotogram#2]

**Comment by karpinovsky** [comment]
@vladimirich CR ples

**Comment by karpinovsky** [comment]
https://serene-forest-94502.herokuapp.com/

**Comment by vladimirich** [comment]
Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details.

**Comment by vladimirich** [comment]
@karpinovsky
